# Generated by Django 5.1.1 on 2024-12-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos\\it-educational-services-1698228802-7144384.jpgphotos/'),
        ),
    ]
